classes:
  - exercises:
      # `file` is relative to .strigo directory
      - file: "../hello-world/hello.md"
        title: "Hello!"
      - file: "../hello-world/world.md"
        title: "World!"
