classes:
  - exercises:
      # `file` is relative to .strigo directory
      - file: "../Essentials-Course/t1-creating-a-datasource.md"
        title: "Creating a Data Source"
      - file: "../Essentials-Course/t1-sharing_datasource.md"
        title: "Sharing a Data Source"
